Models/Cart.cs
namespace SportsStore.Models
{
    public class Cart
    {
        public List<CartLine> Lines { get; set; } = new List<CartLine>();

        public virtual void AddItem(Product product, int quantity)
        {
            CartLine? line = Lines.Where(p => p.Product.ProductId== product.ProductId).FirstOrDefault();

            if(line == null)
            {
                Lines.Add(new CartLine { Product= product, Quantity = quantity });
            }
            else
            {
                line!.Quantity += quantity;
            }
        }

        public virtual void RemoveLine(Product product) => Lines.RemoveAll(l => l.Product.ProductId == product.ProductId);   

        public decimal ComputeTotalValue() => Lines.Sum(e => e.Product.Price * e.Quantity);

        public virtual void Clear() => Lines.Clear();
    }

    public class CartLine
    {
        public int CartLineId { get; set; }
        public Product Product { get; set; } = new();
        public int Quantity { get; set; }
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
namespace SportsStore.Controllers
{
    public class OrderController: Controller
    {
        private IOrderRepository _repository;
        private Cart _cart;
        public OrderController(IOrderRepository orderRepository, Cart cartService)
        {
            _repository= orderRepository;
            _cart= cartService;
        }
        public ViewResult Checkout() => View(new Order());

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if(_cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if(ModelState.IsValid)
            {
                order.CartLines = _cart.Lines.ToArray();
                _repository.SaveOrder(order);  
                _cart.Clear();
                return RedirectToPage("/Completed", new {orderId = order.OrderId});
            }
            else
            {
                return View();
            }
        }
    }
}

Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SportsStore.Infrastructure;

namespace SportsStore.Pages
{
    public class CartModel : PageModel
    {
        private IStoreRepository _storeRepository;
      
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; } = "/";
        public CartModel(IStoreRepository storeRepository, Cart cartService)
        {
            _storeRepository = storeRepository;
            Cart = cartService;
        }
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }
        public IActionResult OnPost(long productId, string returnUrl)
        {
            Product? product = _storeRepository.Products.FirstOrDefault(p => p.ProductId == productId);
            if(product != null)
            {
                Cart.AddItem(product, 1);
            }
            return RedirectToPage(new {returnUrl = returnUrl});
        }

        public IActionResult OnPostRemove(long productId, string returnUrl)
        {
            Cart.RemoveLine(Cart.Lines.First(cl => cl.Product.ProductId == productId).Product);
            return RedirectToPage(new {returnUrl = returnUrl});
        } 
    }
}

Pages/Completed.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SportsStore.Pages
{
    public class CompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SportsStore.Pages
{
    public class ErrorModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Cart.cshtml
@page
@model CartModel

<h2>Your Cart</h2>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Quantity</th>
            <th>Item</th>
            <th class="text-right">Price</th>
            <th class="text-right">Subtotal</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model?.Cart?.Lines ?? Enumerable.Empty<CartLine>())
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Product.Name</td>
                <td class="text-right">@line.Product.Price.ToString("c")</td>
                <td class="text-right">@((line.Quantity * line.Product.Price).ToString("c"))</td>

                <td class="text-center">
                    <form asp-page-handler="Remove" method="post">
                        <input type="hidden" name="ProductId" value="@line.Product.ProductId"/>
                        <input type="hidden" name="returnUrl" value="@Model?.ReturnUrl"/>
                        <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total</td>
            <td class="text-right">@Model?.Cart?.ComputeTotalValue().ToString("c")</td>
        </tr>+
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model?.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-primary" asp-action="Checkout" asp-controller="Order">Checkout</a>
</div>

Pages/Completed.cshtml
@page
@model SportsStore.Pages.CompletedModel
@{
}

<div class="text-center">
    <h2>Thanks</h2>
    <p>Thanks for placing this order #@OrderId</p>
    <a class="btn btn-primary" asp-controller="Home">Return to Store</a>
</div>

@functions{
    [BindProperty(SupportsGet = true)]
    public string? OrderId { get; set; }
}

Pages/_CartLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <title>SportsStore</title>
</head>
<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2"> SPORTS STORE</span>
    </div>
    <div class="m-1 p-1">
         @RenderBody()
    </div>
</body>
</html>